name: Run Maven Test
on: [workflow_dispatch]
jobs:
  run-maven-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.23+9'  # Updated to a valid version
          distribution: 'adopt'
      - name: Install project dependencies
        run: mvn install
      - name: Run Maven tests
        run: mvn test
