name: Run Maven Test
on: [workflow_dispatch]
jobs:
  run-maven-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Set up JDK 1.8
        run: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk
      - name: Install project dependencies
        run: mvn install
      - name: Run Maven tests
        run: mvn test
